version: '3.7'

services:
    db:
        image: mariadb:10.6.5
        container_name: app_maria_db
        environment:
            MYSQL_ROOT_PASSWORD: PASSWORD_ROOT
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - '4306:3306'
        volumes:
            - .db:/var/lib/mysql/
        networks:
            - app
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: app_phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: PASSWORD_ROOT
        networks:
            - app
    php:
        container_name: app_php
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
        volumes:
            - .App:/var/www/symfony
        networks:
            - app
#    nginx:
#        container_name: app_nginx
#        depends_on:
#            - php
#        build:
#            context: .
#            dockerfile: Dockerfile-nginx
#        ports:
#            - 8000:80
#            - 8443:443
#        networks:
#            - app

networks:
    app:

